# The first stage
# Build React static files
FROM node:14-alpine as build
ARG SRC_DIR

WORKDIR /app/frontend
COPY ${SRC_DIR}/package.json ${SRC_DIR}/yarn.lock ./

# COPY ${SRC_DIR}/package-lock.json ./
# RUN npm ci --silent

# COPY ${SRC_DIR}/ ./
RUN yarn global add react-scripts
RUN yarn install --ignore-optional

# start app
CMD ["yarn", "run", "start"]